// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Context {
  "@context": string;
  "@type": string;
  url: string;
  mainEntityOfPage: string;
  prescriptionStatus: string;
  drugUnit: string;
  activeIngredient: string;
  alcoholWarning: string;
  breastfeedingWarning: string;
  foodWarning: null;
  pregnancyWarning: string;
  manufacturer: Manufacturer;
  interactingDrug: null;
  administrationRoute: string;
  isAvailableGenerically: boolean;
  isProprietary: boolean;
  nonProprietaryName: string;
  dosageForm: string;
  description: string;
  name: string;
  proprietaryName: string;
  availableStrength: AvailableStrength[];
  mechanismOfAction: string[];
  doseSchedule: DoseSchedule;
  image: string;
  relevantSpecialty: RelevantSpecialty;
}

export interface AvailableStrength {
  "@type": string;
  activeIngredient: null;
  strengthUnit: string;
  strengthValue: string;
}

export interface DoseSchedule {
  "@type": string;
  doseUnit: string;
  doseValue: string;
  frequency: string;
}

export interface Manufacturer {
  "@type": string;
  legalName: string;
}

export interface RelevantSpecialty {
  "@type": string;
  name: string;
}
